package lexer;/* CLexer.java */
/* Generated By:JavaCC: Do not edit this line. CLexer.java */
import parser.ParserNode;
import java.io.StringReader;
import java.util.Map;
import exception.LexicalException;

public class CLexer implements CLexerConstants {
    private Map<String, Token> symbolTable;
    private Map<String, Token> reservedWordTable;

    public void setTables(Map<String, Token> symbolTable, Map<String, Token> reservedWordTable) {
        this.symbolTable = symbolTable;
        this.reservedWordTable = reservedWordTable;
    }

    private void recordToken() {
        Token t = getToken(0);
        reservedWordTable.putIfAbsent(t.image, t);
    }

    final public void throwSyntacticError(String message) throws ParseException {
        Token currentToken = getToken(0);
        throw new ParseException(message + " (linha: " + currentToken.beginLine + ", coluna: " + currentToken.beginColumn + ").");
    }

// ----------- Regras sintáticas ---------

// Tipos
  final public void typeSpecifier(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("typeSpecifier");
    parent.addChild(node);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case KW_CHAR:{
      jj_consume_token(KW_CHAR);
recordToken(); node.addChild(new ParserNode("KW_CHAR"));
      break;
      }
    case KW_FLOAT:{
      jj_consume_token(KW_FLOAT);
recordToken(); node.addChild(new ParserNode("KW_FLOAT"));
      break;
      }
    case KW_INT:{
      jj_consume_token(KW_INT);
recordToken(); node.addChild(new ParserNode("KW_INT"));
      break;
      }
    case KW_LONG:{
      jj_consume_token(KW_LONG);
recordToken(); node.addChild(new ParserNode("KW_LONG"));
      break;
      }
    case KW_DOUBLE:{
      jj_consume_token(KW_DOUBLE);
recordToken(); node.addChild(new ParserNode("KW_DOUBLE"));
      break;
      }
    case KW_VOID:{
      jj_consume_token(KW_VOID);
recordToken(); node.addChild(new ParserNode("KW_VOID"));
      break;
      }
    case IDENTIFIER:{
      jj_consume_token(IDENTIFIER);
Token t = getToken(0); symbolTable.putIfAbsent(t.image, t); node.addChild(new ParserNode("IDENTIFIER"));
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STAR:{
      jj_consume_token(STAR);
recordToken(); node.addChild(new ParserNode("STAR"));
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
  }

// Argumentos de uma função
  final public void functionArguments(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("functionArguments");
    parent.addChild(node);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:
    case MINUS:
    case NOT:
    case INC:
    case DEC:
    case LPAREN:
    case DECIMAL_LITERAL:
    case INTEGER_LITERAL:
    case CHAR_LITERAL:
    case STRING_LITERAL:
    case IDENTIFIER:{
      expression(node);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          break label_1;
        }
        jj_consume_token(COMMA);
recordToken(); node.addChild(new ParserNode("COMMA"));
        expression(node);
      }
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
  }

// Chamada de uma função
  final public void functionCallStatement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("functionCallStatement");
    parent.addChild(node);
    Token t;
    t = jj_consume_token(IDENTIFIER);
symbolTable.putIfAbsent(t.image, t); node.addChild(new ParserNode("IDENTIFIER"));
    jj_consume_token(LPAREN);
recordToken(); node.addChild(new ParserNode("LPAREN"));
    functionArguments(node);
    jj_consume_token(RPAREN);
recordToken(); node.addChild(new ParserNode("RPAREN"));
    endOfStatement(node);
  }

// parâmetro de uma função
  final public void parameter(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("parameter");
    parent.addChild(node);
    Token t;
    typeSpecifier(node);
    t = jj_consume_token(IDENTIFIER);
symbolTable.putIfAbsent(t.image, t); node.addChild(new ParserNode("IDENTIFIER"));
  }

// parâmetros de uma função
  final public void functionParams(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("functionParams");
    parent.addChild(node);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case KW_CHAR:
    case KW_DOUBLE:
    case KW_FLOAT:
    case KW_INT:
    case KW_LONG:
    case KW_VOID:
    case IDENTIFIER:{
      parameter(node);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          break label_2;
        }
        jj_consume_token(COMMA);
recordToken(); node.addChild(new ParserNode("COMMA"));
        parameter(node);
      }
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
  }

// declaração de uma função
  final public void functionDeclaration(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("functionDeclaration");
    parent.addChild(node);
    Token t;
    typeSpecifier(node);
    t = jj_consume_token(IDENTIFIER);
symbolTable.putIfAbsent(t.image, t); node.addChild(new ParserNode("IDENTIFIER"));
    jj_consume_token(LPAREN);
recordToken(); node.addChild(new ParserNode("LPAREN"));
    functionParams(node);
    jj_consume_token(RPAREN);
recordToken(); node.addChild(new ParserNode("RPAREN"));
    block(node);
  }

// retorno de uma função
  final public void functionReturnStatement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("functionReturnStatement");
    parent.addChild(node);
    jj_consume_token(KW_RETURN);
recordToken(); node.addChild(new ParserNode("KW_RETURN"));
    if (jj_2_1(2)) {
      expression(node);
    } else {
      ;
    }
    endOfStatement(node);
  }

// loop for
  final public void forStatement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("forStatement");
    parent.addChild(node);
    jj_consume_token(KW_FOR);
recordToken(); node.addChild(new ParserNode("KW_FOR"));
    jj_consume_token(LPAREN);
recordToken(); node.addChild(new ParserNode("LPAREN"));
    if (jj_2_2(2147483647)) {
      variableDeclaration(node);
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        assignmentStatement(node);
        break;
        }
      case SEMICOLON:{
        jj_consume_token(SEMICOLON);
recordToken(); node.addChild(new ParserNode("SEMICOLON"));
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    expression(node);
    jj_consume_token(SEMICOLON);
recordToken(); node.addChild(new ParserNode("SEMICOLON"));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:
    case MINUS:
    case NOT:
    case INC:
    case DEC:
    case LPAREN:
    case DECIMAL_LITERAL:
    case INTEGER_LITERAL:
    case CHAR_LITERAL:
    case STRING_LITERAL:
    case IDENTIFIER:{
      expression(node);
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
recordToken(); node.addChild(new ParserNode("RPAREN"));
    statement(node);
  }

// loop while
  final public void whileStatement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("whileStatement");
    parent.addChild(node);
    jj_consume_token(KW_WHILE);
recordToken(); node.addChild(new ParserNode("KW_WHILE"));
    jj_consume_token(LPAREN);
recordToken(); node.addChild(new ParserNode("LPAREN"));
    expression(node);
    jj_consume_token(RPAREN);
recordToken(); node.addChild(new ParserNode("RPAREN"));
    statement(node);
  }

// bloco
  final public void block(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("block");
    parent.addChild(node);
    jj_consume_token(LBRACE);
recordToken(); node.addChild(new ParserNode("LBRACE"));
    label_3:
    while (true) {
      if (jj_2_3(2)) {
        ;
      } else {
        break label_3;
      }
      statement(node);
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RBRACE:{
      jj_consume_token(RBRACE);
recordToken(); node.addChild(new ParserNode("RBRACE"));
      break;
      }
    case 0:{
      jj_consume_token(0);
throwSyntacticError("Erro de sintaxe: o bloco n\u00e3o foi fechado antes do final do arquivo.");
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void conditionalExpression(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("conditionalExpression");
    parent.addChild(node);
    jj_consume_token(LPAREN);
recordToken(); node.addChild(new ParserNode("LPAREN"));
    expression(node);
    jj_consume_token(RPAREN);
recordToken(); node.addChild(new ParserNode("RPAREN"));
  }

  final public void breakStatement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("breakStatement");
    parent.addChild(node);
    jj_consume_token(KW_BREAK);
recordToken(); node.addChild(new ParserNode("KW_BREAK"));
    endOfStatement(node);
  }

  final public void continueStatement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("continueStatement");
    parent.addChild(node);
    jj_consume_token(KW_CONTINUE);
recordToken(); node.addChild(new ParserNode("KW_CONTINUE"));
    endOfStatement(node);
  }

  final public void papibagrifarCaseOnlyGroup(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("papibagrifarCaseOnlyGroup");
    parent.addChild(node);
    label_4:
    while (true) {
      jj_consume_token(KW_CASE);
recordToken(); node.addChild(new ParserNode("KW_CASE"));
      expression(node);
      jj_consume_token(COLON);
recordToken(); node.addChild(new ParserNode("COLON"));
      if (jj_2_4(2)) {
        ;
      } else {
        break label_4;
      }
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case KW_BREAK:
      case KW_CHAR:
      case KW_CONTINUE:
      case KW_DOUBLE:
      case KW_FLOAT:
      case KW_FOR:
      case KW_IF:
      case KW_INT:
      case KW_LONG:
      case KW_PAPIBAGRIFAR:
      case KW_PAPIBAQUIGRAFAR:
      case KW_RETURN:
      case KW_VOID:
      case KW_WHILE:
      case PLUS:
      case MINUS:
      case NOT:
      case INC:
      case DEC:
      case LPAREN:
      case LBRACE:
      case DECIMAL_LITERAL:
      case INTEGER_LITERAL:
      case CHAR_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_5;
      }
      statement(node);
    }
  }

  final public void papibagrifarDefaultGroup(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("papibagrifarDefaultGroup");
    parent.addChild(node);
    jj_consume_token(KW_DEFAULT);
recordToken(); node.addChild(new ParserNode("KW_DEFAULT"));
    jj_consume_token(COLON);
recordToken(); node.addChild(new ParserNode("COLON"));
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case KW_BREAK:
      case KW_CHAR:
      case KW_CONTINUE:
      case KW_DOUBLE:
      case KW_FLOAT:
      case KW_FOR:
      case KW_IF:
      case KW_INT:
      case KW_LONG:
      case KW_PAPIBAGRIFAR:
      case KW_PAPIBAQUIGRAFAR:
      case KW_RETURN:
      case KW_VOID:
      case KW_WHILE:
      case PLUS:
      case MINUS:
      case NOT:
      case INC:
      case DEC:
      case LPAREN:
      case LBRACE:
      case DECIMAL_LITERAL:
      case INTEGER_LITERAL:
      case CHAR_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_6;
      }
      statement(node);
    }
  }

  final public void papibagrifarStatement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("papibagrifarStatement");
    parent.addChild(node);
    jj_consume_token(KW_PAPIBAGRIFAR);
recordToken(); node.addChild(new ParserNode("KW_PAPIBAGRIFAR"));
    jj_consume_token(LPAREN);
recordToken(); node.addChild(new ParserNode("LPAREN"));
    expression(node);
    jj_consume_token(RPAREN);
recordToken(); node.addChild(new ParserNode("RPAREN"));
    jj_consume_token(LBRACE);
recordToken(); node.addChild(new ParserNode("LBRACE"));
    if (jj_2_5(2147483647)) {
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case KW_CASE:{
          ;
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          break label_7;
        }
        papibagrifarCaseOnlyGroup(node);
      }
      papibagrifarDefaultGroup(node);
    } else {
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case KW_CASE:{
          ;
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          break label_8;
        }
        papibagrifarCaseOnlyGroup(node);
      }
{if (true) throw new ParseException("Erro de sintaxe: a instru\u00e7\u00e3o 'papibagrifar' deve conter exatamente um 'default'.");}
    }
    jj_consume_token(RBRACE);
recordToken(); node.addChild(new ParserNode("RBRACE"));
  }

  final public void conditionalStatement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("conditionalStatement");
    parent.addChild(node);
    jj_consume_token(KW_IF);
recordToken(); node.addChild(new ParserNode("KW_IF"));
    conditionalExpression(node);
    statement(node);
    if (jj_2_6(2)) {
      jj_consume_token(KW_ELSE);
recordToken(); node.addChild(new ParserNode("KW_ELSE"));
      statement(node);
    } else {
      ;
    }
  }

  final public void primaryExpression(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("primaryExpression");
    parent.addChild(node);
    Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      t = jj_consume_token(INTEGER_LITERAL);
symbolTable.putIfAbsent(t.image, t); node.addChild(new ParserNode("INTEGER"));
      break;
      }
    case DECIMAL_LITERAL:{
      t = jj_consume_token(DECIMAL_LITERAL);
symbolTable.putIfAbsent(t.image, t); node.addChild(new ParserNode("DECIMAL"));
      break;
      }
    case CHAR_LITERAL:{
      t = jj_consume_token(CHAR_LITERAL);
symbolTable.putIfAbsent(t.image, t); node.addChild(new ParserNode("CHAR"));
      break;
      }
    case STRING_LITERAL:{
      t = jj_consume_token(STRING_LITERAL);
symbolTable.putIfAbsent(t.image, t); node.addChild(new ParserNode("STRING"));
      break;
      }
    case IDENTIFIER:{
      t = jj_consume_token(IDENTIFIER);
symbolTable.putIfAbsent(t.image, t); node.addChild(new ParserNode("IDENTIFIER"));
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
recordToken(); node.addChild(new ParserNode("LPAREN"));
      expression(node);
      jj_consume_token(RPAREN);
recordToken(); node.addChild(new ParserNode("RPAREN"));
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void postfixExpression(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("postfixExpression");
    parent.addChild(node);
    primaryExpression(node);
    if (jj_2_7(2)) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INC:{
        jj_consume_token(INC);
recordToken(); node.addChild(new ParserNode("INC"));
        break;
        }
      case DEC:{
        jj_consume_token(DEC);
recordToken(); node.addChild(new ParserNode("DEC"));
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } else {
      ;
    }
  }

  final public void unaryExpression(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("unaryExpression");
    parent.addChild(node);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:
    case MINUS:
    case NOT:
    case INC:
    case DEC:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INC:{
        jj_consume_token(INC);
recordToken(); node.addChild(new ParserNode("INC"));
        break;
        }
      case DEC:{
        jj_consume_token(DEC);
recordToken(); node.addChild(new ParserNode("DEC"));
        break;
        }
      case PLUS:{
        jj_consume_token(PLUS);
recordToken(); node.addChild(new ParserNode("PLUS"));
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
recordToken(); node.addChild(new ParserNode("MINUS"));
        break;
        }
      case NOT:{
        jj_consume_token(NOT);
recordToken(); node.addChild(new ParserNode("NOT"));
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    postfixExpression(node);
  }

  final public void multiplicativeExpression(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("multiplicativeExpression");
    parent.addChild(node);
    unaryExpression(node);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case STAR:
      case DIVIDE:
      case MODULO:
      case EXPO:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_9;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case STAR:{
        jj_consume_token(STAR);
recordToken(); node.addChild(new ParserNode("MULTIPLY"));
        break;
        }
      case DIVIDE:{
        jj_consume_token(DIVIDE);
recordToken(); node.addChild(new ParserNode("DIVIDE"));
        break;
        }
      case MODULO:{
        jj_consume_token(MODULO);
recordToken(); node.addChild(new ParserNode("MODULO"));
        break;
        }
      case EXPO:{
        jj_consume_token(EXPO);
recordToken(); node.addChild(new ParserNode("EXPO"));
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      unaryExpression(node);
    }
  }

  final public void additiveExpression(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("additiveExpression");
    parent.addChild(node);
    multiplicativeExpression(node);
    label_10:
    while (true) {
      if (jj_2_8(2)) {
        ;
      } else {
        break label_10;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        jj_consume_token(PLUS);
recordToken(); node.addChild(new ParserNode("PLUS"));
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
recordToken(); node.addChild(new ParserNode("MINUS"));
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      multiplicativeExpression(node);
    }
  }

  final public void bitExpression(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("bitExpression");
    parent.addChild(node);
    additiveExpression(node);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case BIT_AND:
      case BIT_XOR:
      case BIT_NOT:
      case LSHIFT:
      case RSHIFT:{
        ;
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case BIT_AND:{
        jj_consume_token(BIT_AND);
recordToken(); node.addChild(new ParserNode("BIT_AND"));
        break;
        }
      case BIT_NOT:{
        jj_consume_token(BIT_NOT);
recordToken(); node.addChild(new ParserNode("BIT_NOT"));
        break;
        }
      case BIT_XOR:{
        jj_consume_token(BIT_XOR);
recordToken(); node.addChild(new ParserNode("BIT_XOR"));
        break;
        }
      case LSHIFT:{
        jj_consume_token(LSHIFT);
recordToken(); node.addChild(new ParserNode("LSHIFT"));
        break;
        }
      case RSHIFT:{
        jj_consume_token(RSHIFT);
recordToken(); node.addChild(new ParserNode("RSHIFT"));
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      additiveExpression(node);
    }
  }

  final public void relationalExpression(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("relationalExpression");
    parent.addChild(node);
    bitExpression(node);
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:
      case NE:
      case LT:
      case GT:
      case LE:
      case GE:{
        ;
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LT:{
        jj_consume_token(LT);
recordToken(); node.addChild(new ParserNode("LT"));
        break;
        }
      case GT:{
        jj_consume_token(GT);
recordToken(); node.addChild(new ParserNode("GT"));
        break;
        }
      case LE:{
        jj_consume_token(LE);
recordToken(); node.addChild(new ParserNode("LE"));
        break;
        }
      case GE:{
        jj_consume_token(GE);
recordToken(); node.addChild(new ParserNode("GE"));
        break;
        }
      case EQ:{
        jj_consume_token(EQ);
recordToken(); node.addChild(new ParserNode("EQ"));
        break;
        }
      case NE:{
        jj_consume_token(NE);
recordToken(); node.addChild(new ParserNode("NE"));
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      bitExpression(node);
    }
  }

  final public void logicalAndExpression(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("andExpression");
    parent.addChild(node);
    relationalExpression(node);
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_13;
      }
      jj_consume_token(AND);
recordToken(); node.addChild(new ParserNode("AND"));
      relationalExpression(node);
    }
  }

  final public void logicalOrExpression(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("logical_or_expression");
    parent.addChild(node);
    logicalAndExpression(node);
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_14;
      }
      jj_consume_token(OR);
recordToken(); node.addChild(new ParserNode("OR"));
      logicalAndExpression(node);
    }
  }

  final public void assignmentOperators(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("assignmentOperators");
    parent.addChild(node);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      jj_consume_token(ASSIGN);
recordToken(); node.addChild(new ParserNode("ASSIGN"));
      break;
      }
    case PLUS_ASSIGN:{
      jj_consume_token(PLUS_ASSIGN);
recordToken(); node.addChild(new ParserNode("PLUS_ASSIGN"));
      break;
      }
    case MINUS_ASSIGN:{
      jj_consume_token(MINUS_ASSIGN);
recordToken(); node.addChild(new ParserNode("MINUS_ASSIGN"));
      break;
      }
    case MULTIPLY_ASSIGN:{
      jj_consume_token(MULTIPLY_ASSIGN);
recordToken(); node.addChild(new ParserNode("MULTIPLY_ASSIGN"));
      break;
      }
    case DIVIDE_ASSIGN:{
      jj_consume_token(DIVIDE_ASSIGN);
recordToken(); node.addChild(new ParserNode("DIVIDE_ASSIGN"));
      break;
      }
    case MODULO_ASSIGN:{
      jj_consume_token(MODULO_ASSIGN);
recordToken(); node.addChild(new ParserNode("MODULO_ASSIGN"));
      break;
      }
    case BIT_XOR_ASSIGN:{
      jj_consume_token(BIT_XOR_ASSIGN);
recordToken(); node.addChild(new ParserNode("BIT_XOR_ASSIGN"));
      break;
      }
    case BIT_AND_ASSIGN:{
      jj_consume_token(BIT_AND_ASSIGN);
recordToken(); node.addChild(new ParserNode("BIT_AND_ASSIGN"));
      break;
      }
    case BIT_OR_ASSIGN:{
      jj_consume_token(BIT_OR_ASSIGN);
recordToken(); node.addChild(new ParserNode("BIT_OR_ASSIGN"));
      break;
      }
    case LSHIFT_ASSIGN:{
      jj_consume_token(LSHIFT_ASSIGN);
recordToken(); node.addChild(new ParserNode("LSHIFT_ASSIGN"));
      break;
      }
    case RSHIFT_ASSIGN:{
      jj_consume_token(RSHIFT_ASSIGN);
recordToken(); node.addChild(new ParserNode("RSHIFT_ASSIGN"));
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void assignmentStatement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("assignmentStatement");
    parent.addChild(node);
    Token t;
    t = jj_consume_token(IDENTIFIER);
symbolTable.putIfAbsent(t.image, t); node.addChild(new ParserNode("IDENTIFIER"));
    assignmentOperators(node);
    expression(node);
    endOfStatement(node);
  }

  final public void importStatement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("import_statement");
    parent.addChild(node);
    Token t;
    jj_consume_token(KW_PAPIBAQUIGRAFAR);
recordToken(); node.addChild(new ParserNode("KW_PAPIBAQUIGRAFAR"));
    t = jj_consume_token(STRING_LITERAL);
symbolTable.putIfAbsent(t.image, t);
    endOfStatement(node);
  }

// Expressão
  final public void expression(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("expression");
    parent.addChild(node);
    logicalOrExpression(node);
  }

  final public void expressionStatement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("expressionStatement");
    parent.addChild(node);
    expression(node);
    endOfStatement(node);
  }

// Declaração
  final public void variableDeclaration(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("variableDeclaration");
    parent.addChild(node);
    Token t;
    typeSpecifier(node);
    t = jj_consume_token(IDENTIFIER);
symbolTable.putIfAbsent(t.image, t); node.addChild(new ParserNode("IDENTIFIER"));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      jj_consume_token(ASSIGN);
recordToken(); node.addChild(new ParserNode("ASSIGN"));
      expression(node);
      break;
      }
    default:
      jj_la1[27] = jj_gen;
      ;
    }
    endOfStatement(node);
  }

// Fim de uma instrução
  final public void endOfStatement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("endOfStatement");
    parent.addChild(node);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SEMICOLON:{
      jj_consume_token(SEMICOLON);
recordToken(); node.addChild(new ParserNode("SEMICOLON"));
      break;
      }
    default:
      jj_la1[28] = jj_gen;
throwSyntacticError("Instru\u00e7\u00e3o sem ponto e v\u00edrgula!");
    }
  }

  final public void ambiguousStatement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("ambiguousStatement");
    parent.addChild(node);
    if (jj_2_9(4)) {
      functionDeclaration(node);
    } else if (jj_2_10(4)) {
      variableDeclaration(node);
    } else if (jj_2_11(4)) {
      functionCallStatement(node);
    } else if (jj_2_12(4)) {
      assignmentStatement(node);
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:
      case NOT:
      case INC:
      case DEC:
      case LPAREN:
      case DECIMAL_LITERAL:
      case INTEGER_LITERAL:
      case CHAR_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:{
        expressionStatement(node);
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

// Instrução
  final public void statement(ParserNode parent) throws ParseException {ParserNode node = new ParserNode("statement");
    parent.addChild(node);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case KW_IF:{
      conditionalStatement(node);
      break;
      }
    case KW_WHILE:{
      whileStatement(node);
      break;
      }
    case KW_FOR:{
      forStatement(node);
      break;
      }
    case KW_PAPIBAGRIFAR:{
      papibagrifarStatement(node);
      break;
      }
    case LBRACE:{
      block(node);
      break;
      }
    case KW_PAPIBAQUIGRAFAR:{
      importStatement(node);
      break;
      }
    case KW_RETURN:{
      functionReturnStatement(node);
      break;
      }
    case KW_BREAK:{
      breakStatement(node);
      break;
      }
    case KW_CONTINUE:{
      continueStatement(node);
      break;
      }
    case KW_CHAR:
    case KW_DOUBLE:
    case KW_FLOAT:
    case KW_INT:
    case KW_LONG:
    case KW_VOID:
    case PLUS:
    case MINUS:
    case NOT:
    case INC:
    case DEC:
    case LPAREN:
    case DECIMAL_LITERAL:
    case INTEGER_LITERAL:
    case CHAR_LITERAL:
    case STRING_LITERAL:
    case IDENTIFIER:{
      ambiguousStatement(node);
      break;
      }
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

// Inicio
  final public void start(ParserNode parent) throws ParseException {
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case KW_BREAK:
      case KW_CHAR:
      case KW_CONTINUE:
      case KW_DOUBLE:
      case KW_FLOAT:
      case KW_FOR:
      case KW_IF:
      case KW_INT:
      case KW_LONG:
      case KW_PAPIBAGRIFAR:
      case KW_PAPIBAQUIGRAFAR:
      case KW_RETURN:
      case KW_VOID:
      case KW_WHILE:
      case PLUS:
      case MINUS:
      case NOT:
      case INC:
      case DEC:
      case LPAREN:
      case LBRACE:
      case DECIMAL_LITERAL:
      case INTEGER_LITERAL:
      case CHAR_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        break label_15;
      }
      statement(parent);
    }
    jj_consume_token(0);
  }

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_3R_122()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_129()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_75()
 {
    if (jj_3R_16()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_100()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_47()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_75()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_28()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_3R_48()) return true;
    if (jj_3R_16()) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_64()
 {
    if (jj_scan_token(KW_PAPIBAGRIFAR)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_scan_token(LBRACE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_122()) {
    jj_scanpos = xsp;
    if (jj_3R_123()) return true;
    }
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_86()
 {
    if (jj_scan_token(RSHIFT_ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_85()
 {
    if (jj_scan_token(LSHIFT_ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_57()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_58()
 {
    if (jj_scan_token(STAR)) return true;
    return false;
  }

  private boolean jj_3R_84()
 {
    if (jj_scan_token(BIT_OR_ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_56()
 {
    if (jj_scan_token(KW_VOID)) return true;
    return false;
  }

  private boolean jj_3R_83()
 {
    if (jj_scan_token(BIT_AND_ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_55()
 {
    if (jj_scan_token(KW_DOUBLE)) return true;
    return false;
  }

  private boolean jj_3R_82()
 {
    if (jj_scan_token(BIT_XOR_ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_54()
 {
    if (jj_scan_token(KW_LONG)) return true;
    return false;
  }

  private boolean jj_3R_81()
 {
    if (jj_scan_token(MODULO_ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_53()
 {
    if (jj_scan_token(KW_INT)) return true;
    return false;
  }

  private boolean jj_3R_80()
 {
    if (jj_scan_token(DIVIDE_ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_52()
 {
    if (jj_scan_token(KW_FLOAT)) return true;
    return false;
  }

  private boolean jj_3R_79()
 {
    if (jj_scan_token(MULTIPLY_ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_44()
 {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_78()
 {
    if (jj_scan_token(MINUS_ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_51()
 {
    if (jj_scan_token(KW_CHAR)) return true;
    return false;
  }

  private boolean jj_3R_77()
 {
    if (jj_scan_token(PLUS_ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_30()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) return true;
    }
    }
    }
    }
    }
    }
    xsp = jj_scanpos;
    if (jj_3R_58()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_76()
 {
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_48()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_76()) {
    jj_scanpos = xsp;
    if (jj_3R_77()) {
    jj_scanpos = xsp;
    if (jj_3R_78()) {
    jj_scanpos = xsp;
    if (jj_3R_79()) {
    jj_scanpos = xsp;
    if (jj_3R_80()) {
    jj_scanpos = xsp;
    if (jj_3R_81()) {
    jj_scanpos = xsp;
    if (jj_3R_82()) {
    jj_scanpos = xsp;
    if (jj_3R_83()) {
    jj_scanpos = xsp;
    if (jj_3R_84()) {
    jj_scanpos = xsp;
    if (jj_3R_85()) {
    jj_scanpos = xsp;
    if (jj_3R_86()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_20()
 {
    if (jj_scan_token(KW_DEFAULT)) return true;
    if (jj_scan_token(COLON)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_44()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_24()
 {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  private boolean jj_3R_71()
 {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_50()
 {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_scan_token(KW_CASE)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(COLON)) return true;
    return false;
  }

  private boolean jj_3R_29()
 {
    if (jj_3R_49()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_50()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_43()
 {
    Token xsp;
    if (jj_3_4()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_4()) { jj_scanpos = xsp; break; }
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_71()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_88()
 {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_87()) return true;
    return false;
  }

  private boolean jj_3R_49()
 {
    if (jj_3R_87()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_88()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_117()
 {
    if (jj_scan_token(NE)) return true;
    return false;
  }

  private boolean jj_3R_116()
 {
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  private boolean jj_3R_69()
 {
    if (jj_scan_token(KW_CONTINUE)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_115()
 {
    if (jj_scan_token(GE)) return true;
    return false;
  }

  private boolean jj_3R_114()
 {
    if (jj_scan_token(LE)) return true;
    return false;
  }

  private boolean jj_3R_113()
 {
    if (jj_scan_token(GT)) return true;
    return false;
  }

  private boolean jj_3R_112()
 {
    if (jj_scan_token(LT)) return true;
    return false;
  }

  private boolean jj_3R_68()
 {
    if (jj_scan_token(KW_BREAK)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_102()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_112()) {
    jj_scanpos = xsp;
    if (jj_3R_113()) {
    jj_scanpos = xsp;
    if (jj_3R_114()) {
    jj_scanpos = xsp;
    if (jj_3R_115()) {
    jj_scanpos = xsp;
    if (jj_3R_116()) {
    jj_scanpos = xsp;
    if (jj_3R_117()) return true;
    }
    }
    }
    }
    }
    if (jj_3R_101()) return true;
    return false;
  }

  private boolean jj_3R_87()
 {
    if (jj_3R_101()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_102()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_89()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_128()
 {
    if (jj_scan_token(RSHIFT)) return true;
    return false;
  }

  private boolean jj_3R_127()
 {
    if (jj_scan_token(LSHIFT)) return true;
    return false;
  }

  private boolean jj_3R_126()
 {
    if (jj_scan_token(BIT_XOR)) return true;
    return false;
  }

  private boolean jj_3R_125()
 {
    if (jj_scan_token(BIT_NOT)) return true;
    return false;
  }

  private boolean jj_3R_124()
 {
    if (jj_scan_token(BIT_AND)) return true;
    return false;
  }

  private boolean jj_3R_91()
 {
    if (jj_scan_token(0)) return true;
    return false;
  }

  private boolean jj_3R_90()
 {
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_111()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_124()) {
    jj_scanpos = xsp;
    if (jj_3R_125()) {
    jj_scanpos = xsp;
    if (jj_3R_126()) {
    jj_scanpos = xsp;
    if (jj_3R_127()) {
    jj_scanpos = xsp;
    if (jj_3R_128()) return true;
    }
    }
    }
    }
    if (jj_3R_110()) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_65()
 {
    if (jj_scan_token(LBRACE)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_3()) { jj_scanpos = xsp; break; }
    }
    xsp = jj_scanpos;
    if (jj_3R_90()) {
    jj_scanpos = xsp;
    if (jj_3R_91()) return true;
    }
    return false;
  }

  private boolean jj_3R_101()
 {
    if (jj_3R_110()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_111()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_23()
 {
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  private boolean jj_3_8()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) return true;
    }
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_62()
 {
    if (jj_scan_token(KW_WHILE)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_110()
 {
    if (jj_3R_25()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_8()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_135()
 {
    if (jj_scan_token(EXPO)) return true;
    return false;
  }

  private boolean jj_3R_42()
 {
    if (jj_3R_70()) return true;
    return false;
  }

  private boolean jj_3R_134()
 {
    if (jj_scan_token(MODULO)) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_41()
 {
    if (jj_3R_69()) return true;
    return false;
  }

  private boolean jj_3R_133()
 {
    if (jj_scan_token(DIVIDE)) return true;
    return false;
  }

  private boolean jj_3R_40()
 {
    if (jj_3R_68()) return true;
    return false;
  }

  private boolean jj_3R_132()
 {
    if (jj_scan_token(STAR)) return true;
    return false;
  }

  private boolean jj_3R_39()
 {
    if (jj_3R_67()) return true;
    return false;
  }

  private boolean jj_3R_38()
 {
    if (jj_3R_66()) return true;
    return false;
  }

  private boolean jj_3R_121()
 {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_37()
 {
    if (jj_3R_65()) return true;
    return false;
  }

  private boolean jj_3R_36()
 {
    if (jj_3R_64()) return true;
    return false;
  }

  private boolean jj_3R_120()
 {
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3R_35()
 {
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3R_34()
 {
    if (jj_3R_62()) return true;
    return false;
  }

  private boolean jj_3R_119()
 {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3R_33()
 {
    if (jj_3R_61()) return true;
    return false;
  }

  private boolean jj_3R_18()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_131()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_132()) {
    jj_scanpos = xsp;
    if (jj_3R_133()) {
    jj_scanpos = xsp;
    if (jj_3R_134()) {
    jj_scanpos = xsp;
    if (jj_3R_135()) return true;
    }
    }
    }
    if (jj_3R_45()) return true;
    return false;
  }

  private boolean jj_3R_118()
 {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_25()
 {
    if (jj_3R_45()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_131()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_63()
 {
    if (jj_scan_token(KW_FOR)) return true;
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_118()) {
    jj_scanpos = xsp;
    if (jj_3R_119()) {
    jj_scanpos = xsp;
    if (jj_3R_120()) return true;
    }
    }
    if (jj_3R_16()) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    xsp = jj_scanpos;
    if (jj_3R_121()) jj_scanpos = xsp;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_92()
 {
    if (jj_3R_103()) return true;
    return false;
  }

  private boolean jj_3_12()
 {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3_11()
 {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_10()
 {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_97()
 {
    if (jj_scan_token(NOT)) return true;
    return false;
  }

  private boolean jj_3_9()
 {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_70()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3_10()) {
    jj_scanpos = xsp;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_3_12()) {
    jj_scanpos = xsp;
    if (jj_3R_92()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_96()
 {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  private boolean jj_3R_95()
 {
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  private boolean jj_3R_94()
 {
    if (jj_scan_token(DEC)) return true;
    return false;
  }

  private boolean jj_3R_93()
 {
    if (jj_scan_token(INC)) return true;
    return false;
  }

  private boolean jj_3R_72()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_93()) {
    jj_scanpos = xsp;
    if (jj_3R_94()) {
    jj_scanpos = xsp;
    if (jj_3R_95()) {
    jj_scanpos = xsp;
    if (jj_3R_96()) {
    jj_scanpos = xsp;
    if (jj_3R_97()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_67()
 {
    if (jj_scan_token(KW_RETURN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_1()) jj_scanpos = xsp;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_60()
 {
    return false;
  }

  private boolean jj_3R_45()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_72()) jj_scanpos = xsp;
    if (jj_3R_73()) return true;
    return false;
  }

  private boolean jj_3R_32()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) return true;
    }
    return false;
  }

  private boolean jj_3R_59()
 {
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3R_22()
 {
    if (jj_scan_token(DEC)) return true;
    return false;
  }

  private boolean jj_3R_21()
 {
    if (jj_scan_token(INC)) return true;
    return false;
  }

  private boolean jj_3R_136()
 {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_99()) return true;
    return false;
  }

  private boolean jj_3R_31()
 {
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_26()
 {
    if (jj_3R_30()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_46()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_65()) return true;
    return false;
  }

  private boolean jj_3_7()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) return true;
    }
    return false;
  }

  private boolean jj_3R_17()
 {
    if (jj_3R_30()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_31()) jj_scanpos = xsp;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_73()
 {
    if (jj_3R_98()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_7()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_109()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_108()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_74()
 {
    if (jj_3R_99()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_136()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_107()
 {
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_46()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_74()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_106()
 {
    if (jj_scan_token(CHAR_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_105()
 {
    if (jj_scan_token(DECIMAL_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_103()
 {
    if (jj_3R_16()) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_104()
 {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_98()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_104()) {
    jj_scanpos = xsp;
    if (jj_3R_105()) {
    jj_scanpos = xsp;
    if (jj_3R_106()) {
    jj_scanpos = xsp;
    if (jj_3R_107()) {
    jj_scanpos = xsp;
    if (jj_3R_108()) {
    jj_scanpos = xsp;
    if (jj_3R_109()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_99()
 {
    if (jj_3R_30()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_16()
 {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_scan_token(KW_ELSE)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_61()
 {
    if (jj_scan_token(KW_IF)) return true;
    if (jj_3R_89()) return true;
    if (jj_3R_18()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_6()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_100()
 {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_19()
 {
    if (jj_3R_43()) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_19()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_66()
 {
    if (jj_scan_token(KW_PAPIBAQUIGRAFAR)) return true;
    if (jj_scan_token(STRING_LITERAL)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_27()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_47()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_130()
 {
    if (jj_3R_43()) return true;
    return false;
  }

  private boolean jj_3R_123()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_130()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_129()
 {
    if (jj_3R_43()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public CLexerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[32];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x20194800,0x0,0x0,0x80000000,0x0,0x20194800,0x0,0x80000000,0x1,0xe0ff5a00,0xe0ff5a00,0x400,0x400,0x0,0x0,0x80000000,0x80000000,0x0,0x0,0x80000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80000000,0xe0ff5a00,0xe0ff5a00,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x2,0x0,0x1c001,0x0,0x0,0x0,0x1c001,0x0,0x1c001,0x1c001,0x0,0x0,0x0,0x18000,0x1c001,0x1c001,0x1e,0x1e,0x1,0x51000000,0x51000000,0xfc0,0xfc0,0x1000,0x2000,0x2a3e0020,0x20,0x0,0x1c001,0x1c001,0x1c001,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x200000,0x0,0x400,0x3e0020,0x400,0x200000,0x200200,0x3e0020,0x100,0x3e00a0,0x3e00a0,0x0,0x0,0x3e0020,0x0,0x0,0x0,0x0,0x0,0x0,0x5,0x5,0x0,0x0,0x0,0x0,0xa,0x0,0x200,0x3e0020,0x3e00a0,0x3e00a0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[12];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public CLexer(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public CLexer(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CLexerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public CLexer(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CLexerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public CLexer(CLexerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(CLexerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[87];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 32; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 87; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 12; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
