/* Generated By:JavaCC: Do not edit this line. CLexerConstants.java */
package lexer;
/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CLexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int KW_BREAK = 9;
  /** RegularExpression Id. */
  int KW_CASE = 10;
  /** RegularExpression Id. */
  int KW_CHAR = 11;
  /** RegularExpression Id. */
  int KW_CONTINUE = 12;
  /** RegularExpression Id. */
  int KW_DEFAULT = 13;
  /** RegularExpression Id. */
  int KW_DOUBLE = 14;
  /** RegularExpression Id. */
  int KW_ELSE = 15;
  /** RegularExpression Id. */
  int KW_FLOAT = 16;
  /** RegularExpression Id. */
  int KW_FOR = 17;
  /** RegularExpression Id. */
  int KW_IF = 18;
  /** RegularExpression Id. */
  int KW_INT = 19;
  /** RegularExpression Id. */
  int KW_LONG = 20;
  /** RegularExpression Id. */
  int KW_PAPIBAGRIFAR = 21;
  /** RegularExpression Id. */
  int KW_PAPIBAQUIGRAFAR = 22;
  /** RegularExpression Id. */
  int KW_RETURN = 23;
  /** RegularExpression Id. */
  int KW_SIGNED = 24;
  /** RegularExpression Id. */
  int KW_SIZEOF = 25;
  /** RegularExpression Id. */
  int KW_STRUCT = 26;
  /** RegularExpression Id. */
  int KW_TYPEDEF = 27;
  /** RegularExpression Id. */
  int KW_UNSIGNED = 28;
  /** RegularExpression Id. */
  int KW_VOID = 29;
  /** RegularExpression Id. */
  int KW_WHILE = 30;
  /** RegularExpression Id. */
  int PLUS = 31;
  /** RegularExpression Id. */
  int MINUS = 32;
  /** RegularExpression Id. */
  int STAR = 33;
  /** RegularExpression Id. */
  int DIVIDE = 34;
  /** RegularExpression Id. */
  int MODULO = 35;
  /** RegularExpression Id. */
  int EXPO = 36;
  /** RegularExpression Id. */
  int ASSIGN = 37;
  /** RegularExpression Id. */
  int EQ = 38;
  /** RegularExpression Id. */
  int NE = 39;
  /** RegularExpression Id. */
  int LT = 40;
  /** RegularExpression Id. */
  int GT = 41;
  /** RegularExpression Id. */
  int LE = 42;
  /** RegularExpression Id. */
  int GE = 43;
  /** RegularExpression Id. */
  int AND = 44;
  /** RegularExpression Id. */
  int OR = 45;
  /** RegularExpression Id. */
  int NOT = 46;
  /** RegularExpression Id. */
  int INC = 47;
  /** RegularExpression Id. */
  int DEC = 48;
  /** RegularExpression Id. */
  int PLUS_ASSIGN = 49;
  /** RegularExpression Id. */
  int MINUS_ASSIGN = 50;
  /** RegularExpression Id. */
  int MULTIPLY_ASSIGN = 51;
  /** RegularExpression Id. */
  int DIVIDE_ASSIGN = 52;
  /** RegularExpression Id. */
  int MODULO_ASSIGN = 53;
  /** RegularExpression Id. */
  int QUESTION = 54;
  /** RegularExpression Id. */
  int COLON = 55;
  /** RegularExpression Id. */
  int BIT_AND = 56;
  /** RegularExpression Id. */
  int BIT_AND_ASSIGN = 57;
  /** RegularExpression Id. */
  int BIT_OR = 58;
  /** RegularExpression Id. */
  int BIT_OR_ASSIGN = 59;
  /** RegularExpression Id. */
  int BIT_XOR = 60;
  /** RegularExpression Id. */
  int BIT_XOR_ASSIGN = 61;
  /** RegularExpression Id. */
  int BIT_NOT = 62;
  /** RegularExpression Id. */
  int BIT_NOT_ASSIGN = 63;
  /** RegularExpression Id. */
  int LSHIFT = 64;
  /** RegularExpression Id. */
  int LSHIFT_ASSIGN = 65;
  /** RegularExpression Id. */
  int RSHIFT = 66;
  /** RegularExpression Id. */
  int RSHIFT_ASSIGN = 67;
  /** RegularExpression Id. */
  int INVALID_OPERATOR = 68;
  /** RegularExpression Id. */
  int LPAREN = 69;
  /** RegularExpression Id. */
  int RPAREN = 70;
  /** RegularExpression Id. */
  int LBRACE = 71;
  /** RegularExpression Id. */
  int RBRACE = 72;
  /** RegularExpression Id. */
  int SEMICOLON = 73;
  /** RegularExpression Id. */
  int COMMA = 74;
  /** RegularExpression Id. */
  int LBRACKET = 75;
  /** RegularExpression Id. */
  int RBRACKET = 76;
  /** RegularExpression Id. */
  int DOT = 77;
  /** RegularExpression Id. */
  int ARROW = 78;
  /** RegularExpression Id. */
  int UNTERMINATED_CHAR = 79;
  /** RegularExpression Id. */
  int MULTIPLE_DECIMAL_POINTS = 80;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 81;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 82;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 83;
  /** RegularExpression Id. */
  int STRING_LITERAL = 84;
  /** RegularExpression Id. */
  int IDENTIFIER = 85;
  /** RegularExpression Id. */
  int INVALID_IDENTIFIER = 86;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<LETTER>",
    "<DIGIT>",
    "\"break\"",
    "\"case\"",
    "\"char\"",
    "\"continue\"",
    "\"default\"",
    "\"double\"",
    "\"else\"",
    "\"float\"",
    "\"for\"",
    "\"if\"",
    "\"int\"",
    "\"long\"",
    "\"papibagrifar\"",
    "\"papibaquigrafar\"",
    "\"return\"",
    "\"signed\"",
    "\"sizeof\"",
    "\"struct\"",
    "\"typedef\"",
    "\"unsigned\"",
    "\"void\"",
    "\"while\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"**\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"++\"",
    "\"--\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"?\"",
    "\":\"",
    "\"&\"",
    "\"&=\"",
    "\"|\"",
    "\"|=\"",
    "\"^\"",
    "\"^=\"",
    "\"~\"",
    "\"~=\"",
    "\"<<\"",
    "\"<<=\"",
    "\">>\"",
    "\">>=\"",
    "<INVALID_OPERATOR>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"->\"",
    "<UNTERMINATED_CHAR>",
    "<MULTIPLE_DECIMAL_POINTS>",
    "<DECIMAL_LITERAL>",
    "<INTEGER_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<INVALID_IDENTIFIER>",
  };

}
