import analyzer.CAnalyzer;
import input.InputHelper;

// Import the classes generated by JavaCC.
// The exact names depend on what you put in PARSER_BEGIN(YourParserName)
// For CLexer.jj, they would be:
// import CLexer; // The parser class
// import Token;    // The Token class (often javacc.Token or a generated one)
// import CLexerConstants; // To access token kinds by name

public class Main {

    public static void main(String[] args) {
        InputHelper inputHelper = new InputHelper();
        
        String filePath = inputHelper.input();
        while (!filePath.equals("0")){
            CAnalyzer analyzer = new CAnalyzer();
            analyzer.analyzeFile(filePath);
            filePath = inputHelper.input();
        }
    }
}